image: node:8

cache:
  paths:
    - node_modules/

stages:
  - test
  - build
  - ship

testing:
  stage: test
  script:
    - yarn install
    - yarn test

compile:
  stage: build
  script:
    - yarn install
    - yarn run build
  artifacts:
    paths:
      - build
  only:
    - develop

pages:
  stage: ship
  script:
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - develop
